export const map = [{
    key: 'Wechat',
    reg: /(micromessenger)\/([\w.]+)/
}, {
    key: 'QQ',
    reg: /(qq)\/([\w.]+)/
}, {
    key: 'DingDing',
    reg: /(aliapp\(dingtalk)\/([\w.]+)/
}, {
    key: 'Alipay',
    reg: /(alipayclient|aliapp\(AP)\/([\w.]+)/
}, {
    key: 'Tabao',
    reg: /(aliapp\(tb)\/([\w.]+)/
}, {
    key: 'Weibo',
    reg: /(weibo).*weibo__([\d.]+)/
}, {
    key: 'Youku',
    reg: /(youku)\/([\w.]+)/
}, {
    key: 'YoukuHD',
    reg: /(youkuhd)\/([\w.]+)/
}, {
    key: 'QZone',
    reg: /(qzone)\/.*_qz_([\d.]+)/
}, {
    key: 'QQBrowser ',
    reg: /(qqbrowser)\/([\w.]+)/
}, {
    key: 'UC',
    reg: /(ucbrowser)\/([\w.]+)/
}, {
    key: 'BaiduBrowser',
    reg: /(baidubrowser)\/([\w.]+)/
}, {
    key: 'Sogou',
    reg: /(sogou[\w]*browser)\/([\w.]+)/
}];
